---
title: "Linear Consensus Model"
output: distill::distill_article
bibliography: bibliography.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


For a long time, opinion dynamics were not studied beyond a scope of a localized group.
There was a very popular empirical paradigm called sociometrics which made it possible to obtain detailed information on the social relationships of people in coherent social groups that were studied over an extended period of time.
The spread and dynamics of opinions were studied either on networks that were obtained like this or in a theoretical framework, but at a similar scope.
Afterall, computers were not readily available to everyone and programming took a lot of effort.

The model that Hegselmann and Krause call the *Classical Model of Opinion Dynamics* [@hegselmann2002opinion] is defined as follows:

We have a group of $n$ agents.
For simplicity, we assume that all agents interact in each step.
This is called [**complete mixing**](./complete-mixing.html).
Each agent has an opinion that is represented by a scalar between $0$ and $1$ with $0$ and $1$ representing the extreme opinions.
An **opinion profile** is thus given by a vector of length $n$ (the agent count) $x(t)$ where $t$ is the current time step and $x_i(t)$ is the opinion of agent $i$ at time $t$.
Additionally, we have a weight matrix $A$ where entry $A_{i, j}$ denotes the weight agent $i$ places on the opinion of agent $j$.
In concrete terms, this can be thought of as how "trustworthy" agent $i$ thinks agent $j$ is.

The opinions at time $t+1$ are computed with a simple weighted average, which in matrix terms would be:

$$
x(t+1) = Ax(t)
$$

Defined in a non-recursive way, this would be:

$$
x(t_n) = A^n(t_0)
$$











